### ISSUE TITLE
train_ucf_rgb ValueError: empty range for randrange() (0,-63, -63)

### ISSUE THREAD

**Issue by kaifeng777** [LossNAN/I3D-Tensorflow#21]
File "/usr/代码/I3D-Tensorflow-master/input_data.py", line 65, in get_data
    s_index = random.randint(0, len(filenames) - num_frames_per_clip)
  File "/usr/lib/python2.7/random.py", line 242, in randint
    return self.randrange(a, b+1)
  File "/usr/lib/python2.7/random.py", line 218, in randrange
    raise ValueError, "empty range for randrange() (%d,%d, %d)" % (istart, istop, width)
ValueError: empty range for randrange() (0,-63, -63)

Do you have any suggestions?Thanks.

**Comment by sungyihsun** [comment]
How to solve ?

**Comment by yangjinghit** [comment]
video文件目录不对，
filename/filename.avi
filename/i
filename/x
filename/y
