### ISSUE TITLE
the arguments of generating optical flow

### ISSUE THREAD

**Issue by leeskyed** [LossNAN/I3D-Tensorflow#5]
Hello, LossNAN!

Would you provide the settings of the 'denseFlow' which generates the optical flow? 
Thank you so much.

**Comment by LossNAN** [comment]
There are no special setting for denseflow, the setting of fps just use 30
or 25

Leesky <notifications@github.com> 于2019年1月8日周二 上午9:39写道：

**Comment by leeskyed** [comment]
Thanks for your reply. I would close this issue.
